[package]
name = "pw"
version = "0.1.0"
authors = ["ajuvercr <arthur.vercruysse@outlook.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
